"""
Day 1 helper: profile the 9 Olist CSV files.

Prints (and writes to docs/profile_output.md) the row count, column count, key
uniqueness and null counts for each file, plus the checks listed in
docs/01_data_profile.md.

Usage (from the repo root):
    python scripts/profile_data.py            # expects CSVs in ./data
    python scripts/profile_data.py path/to/csvs
"""
import sys
from pathlib import Path

import pandas as pd

DATA = Path(sys.argv[1]) if len(sys.argv) > 1 else Path("data")
OUT = Path("docs/profile_output.md")

# file name -> candidate primary key columns
FILES = {
    "olist_orders_dataset.csv": ["order_id"],
    "olist_order_items_dataset.csv": ["order_id", "order_item_id"],
    "olist_order_payments_dataset.csv": ["order_id", "payment_sequential"],
    "olist_order_reviews_dataset.csv": ["review_id"],
    "olist_customers_dataset.csv": ["customer_id"],
    "olist_products_dataset.csv": ["product_id"],
    "olist_sellers_dataset.csv": ["seller_id"],
    "olist_geolocation_dataset.csv": ["geolocation_zip_code_prefix"],
    "product_category_name_translation.csv": ["product_category_name"],
}


def load(name: str) -> pd.DataFrame:
    # dtype=str keeps zip prefixes' leading zeros; utf-8-sig strips a byte-order mark
    return pd.read_csv(DATA / name, dtype=str, encoding="utf-8-sig")


def main() -> None:
    missing = [f for f in FILES if not (DATA / f).exists()]
    if missing:
        sys.exit(f"Missing files in {DATA.resolve()}:\n  " + "\n  ".join(missing))

    lines = ["# Profile output (generated by scripts/profile_data.py)", ""]
    lines += ["| File | Rows | Columns | Key | Duplicate keys | Columns with nulls |",
              "|---|---|---|---|---|---|"]
    frames = {}
    for name, key in FILES.items():
        df = load(name)
        frames[name] = df
        dupes = int(df.duplicated(subset=key).sum())
        null_cols = {c: int(n) for c, n in df.isna().sum().items() if n > 0}
        null_text = ", ".join(f"{c} ({n:,})" for c, n in null_cols.items()) or "none"
        lines.append(f"| {name} | {len(df):,} | {df.shape[1]} | {' + '.join(key)} | {dupes:,} | {null_text} |")

    orders = frames["olist_orders_dataset.csv"]
    customers = frames["olist_customers_dataset.csv"]
    reviews = frames["olist_order_reviews_dataset.csv"]
    payments = frames["olist_order_payments_dataset.csv"]
    products = frames["olist_products_dataset.csv"]

    ts = pd.to_datetime(orders["order_purchase_timestamp"])
    by_month = ts.dt.to_period("M").value_counts().sort_index()

    lines += ["", "## Checks for your notes", ""]
    lines.append(f"- Distinct customer_id: {customers['customer_id'].nunique():,}")
    lines.append(f"- Distinct customer_unique_id: {customers['customer_unique_id'].nunique():,}")
    lines.append(f"- First order: {ts.min()}  |  Last order: {ts.max()}")
    lines.append(f"- Products with no category: {products['product_category_name'].isna().sum():,}")
    lines.append(f"- Orders with more than one review: {(reviews.groupby('order_id').size() > 1).sum():,}")
    lines.append(f"- Orders with more than one payment row: {(payments.groupby('order_id').size() > 1).sum():,}")
    lines += ["", "### order_status counts", "", "| Status | Orders |", "|---|---|"]
    for status, n in orders["order_status"].value_counts().items():
        lines.append(f"| {status} | {n:,} |")
    lines += ["", "### Orders by month (use this to choose your trend-chart range)", "",
              "| Month | Orders |", "|---|---|"]
    for month, n in by_month.items():
        lines.append(f"| {month} | {n:,} |")

    report = "\n".join(lines) + "\n"
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(report, encoding="utf-8")
    print(report)
    print(f"Written to {OUT}")


if __name__ == "__main__":
    main()
