"""
Day 6 helper: independent reconciliation of dashboard numbers.

Recalculates the headline KPIs directly from the raw CSVs with pandas, using the
same business rules as the Power BI model. If Power BI and this script disagree,
one of them has a bug; that's the whole point of reconciling.

Rules mirrored from the model:
  - valid sale = order_status not in {canceled, unavailable}
  - revenue = sum of item price on valid orders
  - customers = distinct customer_unique_id with a valid order
  - delivered = status 'delivered' AND a delivery date exists
  - late = delivery date (day) after estimated date (day)
  - review per order = latest by review_answer_timestamp

Usage (from the repo root):
    python scripts/reconcile.py              # expects CSVs in ./data
    python scripts/reconcile.py path/to/csvs
Writes docs/reconciliation_expected.md
"""
import sys
from pathlib import Path

import pandas as pd

DATA = Path(sys.argv[1]) if len(sys.argv) > 1 else Path("data")
OUT = Path("docs/reconciliation_expected.md")
INVALID = {"canceled", "unavailable"}


def read(name: str, **kw) -> pd.DataFrame:
    return pd.read_csv(DATA / name, encoding="utf-8-sig", **kw)


def main() -> None:
    orders = read("olist_orders_dataset.csv", parse_dates=[
        "order_purchase_timestamp", "order_delivered_customer_date", "order_estimated_delivery_date"])
    items = read("olist_order_items_dataset.csv")
    customers = read("olist_customers_dataset.csv", dtype={"customer_zip_code_prefix": str})
    reviews = read("olist_order_reviews_dataset.csv", parse_dates=["review_answer_timestamp"])

    # ---- Sales (item grain)
    sales = items.merge(orders[["order_id", "customer_id", "order_status", "order_purchase_timestamp"]],
                        on="order_id", how="left")
    valid = sales[~sales["order_status"].isin(INVALID)]
    revenue = valid["price"].sum()
    freight = valid["freight_value"].sum()
    n_orders = valid["order_id"].nunique()
    n_items = len(valid)
    n_customers = valid.merge(customers[["customer_id", "customer_unique_id"]], on="customer_id")[
        "customer_unique_id"].nunique()

    # ---- Delivery (order grain)
    delivered = orders[(orders["order_status"] == "delivered")
                       & orders["order_delivered_customer_date"].notna()].copy()
    delivered["days"] = (delivered["order_delivered_customer_date"]
                         - delivered["order_purchase_timestamp"]).dt.days
    delivered["late"] = (delivered["order_delivered_customer_date"].dt.normalize()
                         - delivered["order_estimated_delivery_date"].dt.normalize()).dt.days > 0

    # ---- Reviews (latest per order)
    latest = (reviews.sort_values("review_answer_timestamp")
                     .groupby("order_id", as_index=False).tail(1)[["order_id", "review_score"]])
    o = orders.merge(latest, on="order_id", how="left")
    o = o.merge(delivered[["order_id", "late"]], on="order_id", how="left")
    avg_review = o["review_score"].mean()
    avg_review_late = o.loc[o["late"].eq(True), "review_score"].mean()
    avg_review_ontime = o.loc[o["late"].eq(False), "review_score"].mean()

    # ---- Revenue by year (for YoY checks)
    by_year = valid.groupby(valid["order_purchase_timestamp"].dt.year)["price"].sum()

    rows = [
        ("Revenue", f"{revenue:,.2f}"),
        ("Freight", f"{freight:,.2f}"),
        ("Orders", f"{n_orders:,}"),
        ("Items Sold", f"{n_items:,}"),
        ("AOV", f"{revenue / n_orders:,.2f}"),
        ("Items per Order", f"{n_items / n_orders:.2f}"),
        ("Customers", f"{n_customers:,}"),
        ("Delivered Orders", f"{len(delivered):,}"),
        ("Late Delivery %", f"{delivered['late'].mean():.1%}"),
        ("Avg Delivery Days", f"{delivered['days'].mean():.1f}"),
        ("Avg Review Score", f"{avg_review:.2f}"),
        ("Avg Review (Late)", f"{avg_review_late:.2f}"),
        ("Avg Review (On Time)", f"{avg_review_ontime:.2f}"),
    ]
    rows += [(f"Revenue {int(y)}", f"{v:,.2f}") for y, v in by_year.items()]

    lines = ["# Expected values (generated by scripts/reconcile.py)", "",
             "Compare each value with the matching card in Power BI (no slicers applied).", "",
             "| Measure | Expected (pandas) | Power BI | Match? |", "|---|---|---|---|"]
    lines += [f"| {m} | {v} | [ ] | [ ] |" for m, v in rows]
    report = "\n".join(lines) + "\n"
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(report, encoding="utf-8")
    print(report)
    print(f"Written to {OUT}")


if __name__ == "__main__":
    main()
